services:
  api:
    build: .
    env_file: .env
    restart: always
    expose:
      - "3000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${PORT:-3000}/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:2
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./public:/srv/public:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      api:
        condition: service_healthy

volumes:
  caddy_data:
  caddy_config:
